### ISSUE TITLE
마지막 주

### ISSUE THREAD

**Issue by lndoorshoes** [lndoorshoes/study#13]
# Chp 18 쿠버네티스의 확장
- API 오브젝트 정의 및 오브젝트 컨트롤러 만들기
- PaaS 솔루션 구축

## 18.1 사용자 정의 API 오브젝트 정의
- 전체 어플리케이션을 나타내는 오브젝트를 생성 관리할 수 있다
- 사용자 정의 컨트롤러가 필요한 시크릿, deployment 등 인스턴스를 생성하도록 하면 됨

### 18.1.1 Custom Resource Definition
- 다른 쿠버네티스 리소스 처럼 매니페스트를 API 서버에 개시하여 인스턴스를 만들 수 있다

#### 예제 소개
- 정적 웹사이트를 쉽게 실행하는 오브젝트
- 다른 인스턴스를 삭제, 생성, 검색하는 것과 명령어가 같다

#### 오브젝트 생성
- 마찬가지로 매니페스트를 통해 생성한다
- n2c에는 어떤 CRD가 있을까? 
  - 사용자가 직접 생성하는 것은 허용하고 있지 않다
  - Kafka, ES, Jenkins, vitess, Spark, ACG, NAT..

### 18.1.2 사용자 정의 컨트롤러로 사용자 정의 리소스 자동화
- 컨트롤러가 디플로이먼트 리소스를 생성하도록 하자

#### 컨트롤러 동작 이해
- 컨트롤러는 사이드카 컨테이너로 실행돼 API 서버로의 게이트역할을 하는 kubectl proxy 프로세스에 연결한다
- API 서버는 커스텀 오브젝트의 모든 변경에 대한 감시 이벤트를 보낸다
- 커스텀 오브젝트 생성 이벤트를 컨트롤러가 수신하면 매니페스트를 게시하고, 디플로이먼트, 서비스 오브젝트를 생성함
- 삭제도 이와 거의 같다

#### 파드 형태로 컨트롤러 실행
- 컨트롤러를 디플로이먼트 리소스로 배포할 수도 있다
  - 컨테이너 두 개를 갖는 레플리카 하나를 배포함 (하나는 컨트롤러, 하나는 앰배서더 컨테이너)
  - 여기에서 사용된 서비스 어카운트는 컨트롤러 배포 전에 만들어져야 한다
    - RBAC가 활성화된 경우 클러스터롤바인딩이 필요하다
    
### 18.1.3 CRD 유효성 검증 
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validation-rules:
                - rule: "self.minReplicas <= self.replicas"
                  message: "replicas should be greater than or equal to minReplicas."
                - rule: "self.replicas <= self.maxReplicas"
                  message: "replicas should be smaller than or equal to maxReplicas."
              properties:
                cronSpec:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```
- [Custom resources are validated via OpenAPI v3 schemas, by x-kubernetes-validations when the Validation Rules feature is enabled, and you can add additional validation using admission webhooks.](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation)

### 18.1.4 사용자 정의 오브젝트를 위한 사용자 정의 API 서버 제공
- API 서버 애그리게이션
  - 여러 API 가 사실 서로 다른 오브젝트를 처리하고 있으며, 애그리게이터를 통해 단일 서버로 노출한다
  - 코어 쿠버네티스 APi 서버가 오브젝트를 확인하고 유효성을 검사하도록 할 수 있다
  - 이 때는 오브젝트 유형을 API 서버에 직접 구현, CRD가 필요없다 (이 방법이 좋으려나)

#### 사용자 정의 API 서버 등록
- APIService 리소스 생성, 마찬가지로 파드로 배포하고 서비스를 통해 노출해야 한다

#### 사용자 정의 클라이언트 생성
- 사용자 정의 CLI 도구를 빌드할 수도 있다
- 오브젝트 조작을 위한 전용 명령어 추가 가능

## 18.2 쿠버네티스 서비스 카탈로그를 통한 쿠버네티스 확장+
- 서비스 생성 또는 관리에 대한 자세한 지식 없이도 서비스 브로커를 통해 외부의 매니지드 서비스의 목록과 프로비전, 바인딩하는 방법을 제공한다.
  - ex postgreSQL 데이터 베이스 생성해줘, 하나를 프로비저닝하고 어디서 어떻게 연결하는지 알려줘

### 18.2.1 서비스 카탈로그
- 카탈로그에 나열된 서비스 인스턴스를 프로비저닝할 수 있다
- ClusterServiceBroker: 프로비저닝 가능한 시스템 기술
- ClusterServiceClass: 프로비저닝 가능한 서비스 유형 (브로커로부터 제공 가능한 서비스 목록을 받아 쿠버네티스에서 생성함)
- ServiceInstance: 프로비저닝된 서비스의 인스턴스 
- ServiceBinding: 클라이언트 파드와 인스턴스 간의 바인딩을 나타냄

### 18.2.2 서비스 카탈로그 API 서버, 컨트롤러 매니저 소개
- 카탈로그에 하나이상의 외부 servicebroker를 등록할 수 있다
- 모든 브로커는 openservicebroker를 구현해야 한다
  - 카탈로그는 다음의 API로 브로커와 통신함
  - 서비스 목록 검색, 인스턴스 프로비저닝, 인스턴스 업데이트, 해제, 바인딩 등등
 
#### 카탈로그에 브로커 등록
- servicebroker 리소스 매니페스트를 서비스 카탈로그에 게시하여 등록함
  - 관리자가 clusterservicebroker를 생성한 후 카탈로그 컨트롤러 매니저의 컨트롤러는 브로커가 프로비저닝할 수 있는 서비스 목록을 브로커 리소스가 지정하는 url을 통해 검색한다
  - 이후 각 서비스에 대해 clusterserviceclass를 생성한다 (클래스마다 존재하는 플랜을 보고, 필요한 것을 선택함)
- 사용 가능한 서비스 조회 = kubectl get clusterserviceclasses

### 18.2.4 프로비저닝과 서비스 사용
- 자, ClusterServiceClass 목록을 보고 사용 가능한 것 중 postgres-database ClusterServiceClass의 무료 플랜을 사용하기로 했다고 하자

#### 서비스인스턴스 프로비저닝
- clusterServicePlanName 필드로 플랜을 지정함 (브로커 설명서를 참고했다고 가정)
- 서비스 카탈로그는 서비스를 생성하자 마자 브로커에 접속해 서비스 프로비저닝을 요청한다
  - 이후 브로커는 적절한 처리를 하고, 서비스 인스턴스를 확인할 수 있다

#### 서비스 인스턴스 바인딩
- 이제 서비스 인스턴스를 사용하려면 서비스 바인딩 리소스를 생성해야 한다
- 브로커가 응답한 데이터베이스 연결에 필요한 자격증명, 기타 데이터는 서비스 카탈로그에 전달됨
- 서비스 카탈로그는 service binding에 지정한 이름으로 시크릿을 생성하고 모든 데이터를 시크릿에 저장함

#### 클라이언트 파드에서 새로 생성된 시크릿 사용
- 생성된 시크릿을 사용해 만들어진 인스턴스와 연결할 수 있다
- 파드를 미리 배포해놓을 수도 있다 (시크릿이 만들어지기전에 시작되지 않는다)
- 파드마다 자격증명세트를 만들면 servicebinding을 삭제하여 파드가 서비스를 사용못하게 할 수 있다?
  - 이렇게하면 뭐가 좋을까 (바로 아래 나오네)

### 18.2.5 바인딩 해제와 프로비저닝 해제
- 바인딩만 삭제: kubectl delete servicebinding my-binding
- 인스턴스 삭제도 마찬가지임

### 18.2.6 서비스 카탈로그의 이점 이해
- 쿠버네티스에서 서비스를 쉽게 프로비저닝, 노출까지 가능하게 함(배포가 쉬워진다)

![image](https://user-images.githubusercontent.com/26867199/146778812-36d24693-086e-432f-8210-e0f6544c5051.png)
