### ISSUE TITLE
19장

### ISSUE THREAD

**Issue by lndoorshoes** [lndoorshoes/study#5]
# 13장 클러스터 노드와 네트워크 보안
## 13.1 파드에서 호스트 노드의 네임스페이스 사용
- 파드는 고유한 네트워크 네임스페이스를 사용 = 고유한 IP, 포트 공간, 고유한 PID 네임스페이스, 프로세스 트리, 고유한 IPC 네임스페이스를 사용함

### 13.1.1 파드에서 노드의 네트워크 네임스페이스 사용
- 일반적으로 가상 네트워크 어댑터 사용
- 노드의 실제 네트워크 사용을 위해서는 파드 스펙에서 hostNetwork 속성: true -> 이 경우 노드의 IP, 포트에 바인드 된다
- 호스트 네트워크를 사용하는 파드 네트워크 인터페이스 확인
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-network
spec:
  hostNetwork: true     # 호스트 노드 네트워크 네임스페이스 사용
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
```

### 13.1.2 호스트 네트워크 네임스페스를 사용하지 않고 호스트 포트에 바인딩
- 위의 경우 여전히 고유한 네트워크 네임스페이스를 가진다
- hostPort를 사용하는 파드와 NodePort 서비스로 노출된 파드의 차이
![image](https://user-images.githubusercontent.com/26867199/136700907-869ff8bf-08f9-415d-b57d-8b96f67f496c.png)

- hostPort 기능은 기본적으로 데몬셋을 사용해 모든 노드에 배포되는 시스템 서비스를 노출하는 데 사용된다.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubia-hostport
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080   # 컨테이너에 파드 IP의 포트 8080으로 연결 가능
      hostPort: 9000            # 특정 노드의 포트 9000에서 연결 가능
      protocol: TCP
```

### 13.1.3 노드의 PID와 네임스페이스 사용
- hostNetwork 옵션과 유사한 파드 스펙 속성에 hostPID와 hostIPC이 있음
- 노드의 PID와 IPC 네임스페이스를 사용해 컨테이너에서 실행중인 프로세스가 노드의 다른 프로세스를 보거나 IPC로 통신 가능
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-pid-and-ipc
spec:
  hostPID: true   # 파드가 호스트의 PID 네임스페이스를 사용하도록 한다.
  hostIPC: true   # 파드가 호스트의 IPC 네임스페이스를 사용하도록 한다.
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
```
- 컨테이너의 실행중인 프로세스 뿐만 아니라 호스트 노드에서 실행중인 모든 프로세스가 조회됨

#### 파드에서 프로세스 확인
```bash
kubectl exec pod-with-host-pid-and-ipc ps aux
```

## 13.2 컨테이너의 보안 컨텍스트 구성
- securityContext속성으로 다른 보안 관련 기능을 파드와 파드의 컨테이너에 구성할수 있다.
#### 보안 컨텍스트에서 설정할 수 있는 사항
- 컨테이너의 프로세스를 실행할 사용자 지정
- 컨테이너가 루트로 실행되는것 방지하기
- 컨테이너를 특권모드로 실행해 노드의 커널에 관한 모든 접근 권한을 부여
- 특권모드에서 컨테이너를 실행해 기능을 추가하거나 삭제해 세분화된 권한 구성하기
- 컨테이너의 권한 확인을 강력하게 하기 위해 SELinux(Security Enhanced Linux)옵션 설정하기
- 프로세스가 컨테이너의 파일시스템에 쓰기 방지하기
- 보안 컨텍스트를 지정하지 않고 파드 실행

#### 기본 보안 컨텍스트 옵션을 사용해 파드 실행
```bash
$ kubectl run pod-with-defaults --image alpine --restart Never -- /bin/sleep 999999
```

#### 컨테이너가 어떤 사용자와 그룹 ID로 실행되고 있는지 확인
```bash
$ kubectl exec pod-with-defaults id
```

- 컨테이너가 사용자 ID(uid) 0과 그룹 ID(gid) 0인 루트 사용자로 실행 중임
- 보통 컨테이너 이미지에 지정된 사용자로 컨테이너가 실행되는데 Dockerfile에서 이것은 USER 지시문을 이용하고 생략시 루트 권한으로 실행됨

### 13.2.1 컨테이너를 특정 사용자로 실행
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-as-user-guest
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:       
      runAsUser: 405  # 사용자 이름이 아닌 사용자 ID를 지정
```
#### id 확인
```
$ kubectl exec pod-as-user-guest id
```

### 13.2.2 컨테이너가 루트로 실행되는 것 방지
- 호스트 디렉터리가 컨테이너에 마운트 될 때 컨테이너에서 실행 중인 프로세스가 루트인 경우 마운트된 디렉터리에 권한 있음(이것은 의도하지 않은 것일 가능성이 높음, 루트가 아니면 권한 없음)
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsNonRoot: true     # 루트가 아닌 사용자로만 실행 가능
```

#### pod 상태 확인
```
$ kubectl get po pod-run-as-non-root
```

### 13.2.3 특권 모드에서 파드 실행
때때로 파드는 일반 컨테이너에서 접근할 수 없는 보호된 시스템 장치나 커널의 다른 기능을 사용하는 것과 같이 그들이 실행중인 노드가 할 수 있는 모든 것을 해야 할 수도 있다.
대표적으로는 kube-proxy파드가 있다.(노드의 iptables 규칙을 수정해야 함)
노드 커널의 모든 엑세스 권한을 얻기 위해 파드의 컨테이너는 특권 모드(privileged mode)로 실행된다.
securityContext 속성에서 privileged 속성을 true로 설정하고 실행하면 된다.
apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: true    # 이 컨테이너는 특권 모드에서 실행된다.
/dev 하위에는 장치와 통신하는 데 사용되는 특별한 파일들이 있는데 일반 파드와 특권모드의 파드에서 접근할수 있는 데이터의 양이 다르다.
권한이 있는 컨테이너는 모든 호스트 노드의 장치를 볼수 있음
# 특권모드 파드 생성
kubectl create -f pod-privileged.yaml

# 기본 파드 /dev 확인
kubectl exec -it pod-with-defaults ls /dev
13.2.4 컨테이너에 개별 커널 기능 추가
수년동안 리눅스 커널 기능의 발달로 훨씬 세분화된 권한 시스템을 지원하게 되었다.
보안 관점에서 훨씬 안전한 방법은 컨테이너를 만들때 실제로 필요한 커널 기능만 엑세스하도록 하는 것이다.
컨테이너 권한을 미세 조정하고 공격자의 잠재적인 침입의 영향을 제한할 수 있다.
시스템 시간을 변경하는 예제
컨테이너는 일반적으로 시스템 시간(하드웨어 시계 시간)을 변경할 수 없음
# 파드 시스템 시간 변경(불가능함)
kubectl exec -it pod-with-defaults -- date +%T -s "12:00:00"
스크린샷 2020-09-13 오후 5 28 23

컨테이너 기능에 TIME 기능 추가
apiVersion: v1
kind: Pod
metadata:
  name: pod-add-settime-capability
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      capabilities:
        add:
        - SYS_TIME    # SYS_TIME 기능을  추가
리눅스 커널 기능은 일반적으로 CAP_ 접두어로 시작한다.(파드 스펙에서 지정한 경우 접두어를 생략해야 함)
# 시간 변경 기능을 탑재한 컨테이너를 가진 파드 생성
kubectl create -f pod-add-settime-capability.yaml

# 컨테이너 시간 변경(변경 명령이 동작함)
kubectl exec -it pod-add-settime-capability -- date +%T -s "12:00:00"

# 시간 조회(명령은 동작하나 실제 시간이 변경되지는 않음)
kubectl exec -it pod-add-settime-capability -- date
스크린샷 2020-09-13 오후 5 32 05

모든 권한을 부여하는 특권모드(privileged:true)를 하는것보다 위와 같이 기능을 추가하여 컨테이너에 부여하는 것이 훨씬 좋은 방법이다.
13.2.5 컨테이너에서 기능 제거
컨테이너에 커널 기능을 추가한것처럼 기능을 제거할수도 있따.
파일의 소유권을 변경할 수 있는 CAP_CHOWN 권한은 기본적으로 포함되는 기능인데 이를 제거할수도 있다.
apiVersion: v1
kind: Pod
metadata:
  name: pod-drop-chown-capability
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      capabilities:
        drop:
        - CHOWN     # 이 컨테이너는 파일 소유권을 변경할 수 없다.(기능 제거)
# CHOWN 권한이 없는 파드생성
kubectl create -f pod-drop-chown-capability.yaml

#  CHOWN 권한이 없는 파드에서 소유권 변경 시도
kubectl exec pod-drop-chown-capability chown guest /tmp

#  CHOWN 권한이 있는 파드에서 소유권 변경 시도(정상동작)
kubectl exec pod-with-defaults chown guest /tmp
스크린샷 2020-09-13 오후 5 37 44

13.2.6 프로세스가 컨테이너의 파일시스템에 쓰는 것 방지
컨테이너의 파일시스템에 쓰지 못하게 하고 마운트된 볼륨에만 쓰도록 할 수 있다.
만약 공격자가 파일시스템에 쓸수 있도록 숨겨진 취약점이 있는 애플리케이션을 실행한다고 했을때 공격자가 파일을 수정해 악성 코드를 삽입할 수도 있는데, 이런 공격 유형은 컨테이너가 파일 시스템을 쓰지 못하게 함으로써 방지할 수 있다.
securityContext.readOnlyRootFileSystem 속성을 true로 하면 된다.
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonly-filesystem
spec:
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      readOnlyRootFilesystem: true      # 이 컨테이너는 파일시스템에 쓸수 없다.
    volumeMounts:
    - name: my-volume
      mountPath: /volume                  # 마운트된 볼륨인 /volume에는 쓸 수 있음.
      readOnly: false
  volumes:
  - name: my-volume
    emptyDir:
# 파일시스템에 파일을 쓸수 없는 파드 생성
kubectl create -f pod-with-readonly-filesystem.yaml

# 파일시스템에 파일을 쓸수 없는 파드에서 파일 생성(불가)
kubectl exec -it pod-with-readonly-filesystem touch /new-file

# 볼륨에 파일 생성(성공)
kubectl exec -it pod-with-readonly-filesystem touch /volume/new-file

# 볼륨 파일 확인
kubectl exec -it pod-with-readonly-filesystem -- ls -la /volume/new-file

# 파일시스템에 쓸수있는 파드에서 파일 생성(성공)
kubectl exec -it pod-with-defaults touch /new-file

# 파일시스템에 쓸수 있는 파드 파일 확인
kubectl exec -it pod-with-defaults -- ls -la /new-file
스크린샷 2020-09-13 오후 5 58 45

컨테이너의 파일시스템을 읽기 전용으로 만들 경우 애플리케이션이 쓰는 모든 디렉터리에 볼륨을 마운트해야 한다.
프로덕션 환경에서 보안을 강화하려면 파드를 실행할 때 컨테이너의 readOnlyRootFilesystem 속성을 true로 설정하는 것이 좋다.
파드 수준의 보안 컨텍스트 옵션 설정
컨테이너 수준에서 설정하듯이 팓 ㅡ수준에서도 보안 컨텍스트를 사용할수도 있다.
13.2.7 컨테이너가 다른 사용자로 실행될 때 볼륨 공유
볼륨을 통해 파드의 컨테이너간 데이터 공유를 쉽게 할 수 있는데 이 케이스는 사실 두 컨테이너 모두 루트 권한으로 실행되어 볼륨의 모든 파일에 대한 전체 엑세스 권한을 부여받았기 떄문이다.
runAsUser 옵션을 통해 2개의 컨테이너를 두 명의 다른 사용자로 실행해야 하는 경우가 있다.(이 경우에 항상 서로의 파일을 읽고 쓸수 있는것은 아니다)
쿠버네티스에서는 실행중인 모든 파드에 supplementalGroups 속성을 지정해 실행중인 사용자 ID에 상관없이 파일을 공유할 수 있다.
fsGroup
supplementalGroups
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-shared-volume-fsgroup
spec:
  securityContext:
    fsGroup: 555                # fsGorup과 supplementalGroups는 파드 레벨의 보안 컨텍스트로 정의
    supplementalGroups: [666, 777]
  containers:
  - name: first
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 1111      # 첫번쨰 컨테이너의 사용자 ID : 1111
    volumeMounts:
    - name: shared-volume
      mountPath: /volume
      readOnly: false
  - name: second
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      runAsUser: 2222        # 두번째 컨테이너의 사용자 ID : 2222
    volumeMounts:
    - name: shared-volume     # 각 컨테이너는 같은 볼륨을 사용
      mountPath: /volume
      readOnly: false
  volumes:
  - name: shared-volume
    emptyDir:
# 파드 생성
kubectl create -f pod-with-shared-volume-fsgroup.yaml

# id 확인
kubectl exec -it pod-with-shared-volume-fsgroup -c first sh

# 파드 내부에서 볼륨 확인
 ls -l / | grep volume
스크린샷 2020-09-13 오후 6 08 20

파드 정의에 지정한대로 컨테이너가 사용자 ID 1111로 실행되며, 유효 그룹은 0(root)이지만 그룹 ID 555,666,777도 사용자와 연관이 돼 있다.
fsGroup을 55로 설정했기 때문에 volume은 555 그룹 소유가 된다.
마운트된 볼륨 디렉터리에 파일을 작성하면 사용자 ID 1111과 그룹 ID 555가 소유하게 된다.
스크린샷 2020-09-13 오후 6 13 13

볼륨이 아닌 파일시스템에 생성한다면 root 그룹이 소유하게 된다.(일반적인 사용자 유효 그룹ID가 0[root]이므로)
스크린샷 2020-09-13 오후 6 15 21

fsGroup 보안 컨텍스트 속성은 프로세스가 볼륨에 파일을 생성할 때 사용됨.
supplementalGroups 속성은 사용자와 관련된 추가 그룹 ID 목록을 정의하는 데 사용된다.
아마도 다른 파드같은곳에서 다른 fsGroup으로 해당 그룹ID들을 사용할수 있고, 이에 따른 권한 이용을 위한 목적으로 쓸수 있는듯?
