### ISSUE TITLE
20주

### ISSUE THREAD

**Issue by lndoorshoes** [lndoorshoes/study#6]
## 13.3 파드의 보안 기능 사용 제안
- PSP(pod security policy)리소스는 보안 기능 사용 제한하는 역할

### 13.3.1 PSP
- PSP는 클러스터 수준 리소스, 파드에서 사용 가능한/불가능한 보안 기능 정의

#### 가능한 작업의 목록
- https://kubernetes.io/ko/docs/concepts/policy/pod-security-policy/#%ED%8C%8C%EB%93%9C-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%ED%8F%B4%EB%A6%AC%EC%8B%9C%EB%9E%80
- 특권을 가진 컨테이너, 호스트 포트, 파일시스템 그룹, 루트 파일시스템 사용 여부 등

#### PSP 예제
- 미니쿠베 실행
```
$ minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy
```
- 파드의 호스트 IPC, PID, 네트워크 네임스페이스 사용 방지
```yaml
$ kubectl create -f pod-security-policy.yaml
podsecuritypolicy.policy/default created

$ kubectl get psp
NAME      PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
default   false          RunAsAny   RunAsAny    RunAsAny   RunAsAny   true             *

$ kubectl describe psp
Name:         default
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  policy/v1beta1    # 1.25v 에서 deprecated
Kind:         PodSecurityPolicy
Metadata:
  Creation Timestamp:  2021-10-18T12:25:22Z
  Managed Fields:
    API Version:  policy/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:allowPrivilegeEscalation:
        f:fsGroup:
          f:rule:
        f:hostPorts:
        f:readOnlyRootFilesystem:
        f:runAsUser:
          f:rule:
        f:seLinux:
          f:rule:
        f:supplementalGroups:
          f:rule:
        f:volumes:
    Manager:         kubectl-create
    Operation:       Update
    Time:            2021-10-18T12:25:22Z
  Resource Version:  610
  UID:               9126a10f-8945-4891-a64f-a4a6c44ea4fe
Spec:
  Allow Privilege Escalation:  true
  Fs Group:
    Rule:  RunAsAny
  Host Ports:
    Max:                      11000
    Min:                      10000
    Max:                      14000
    Min:                      13000
  Read Only Root Filesystem:  true
  Run As User:
    Rule:  RunAsAny
  Se Linux:
    Rule:  RunAsAny
  Supplemental Groups:
    Rule:  RunAsAny
  Volumes:
    *
Events:  <none>
```

- 위 리소스에 따라 특권이 있는 파드는 배포 불가능해질까?
  - PSP를 사용하려면 요청 사용자 또는 대상 파드의 서비스 어카운트 정책이 PSP를 use할 권한이 있어야 한다

- 서비스 어카운트 생성
```
$ kubectl create serviceaccount -n default fake-user
```
 
- Cluster role 생성
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-cr
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - default
  verbs:
  - use
```

- Cluster role binding 생성
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-crb
subjects:
- kind: ServiceAccount
  name: fake-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-cr
```

- 결과 확인
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
spec:
  serviceAccountName: fake-user           ## service account 추가
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      privileged: true

```

```bash 
$ kubectl create -f pod-privileged.yaml

Error from server (Forbidden): error when creating "pod-privileged.yaml": pods "pod-privileged" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```

### 13.3.2 runAsUser, fsGroup, supplementalGroups
- RunAsAny 규칙: 제한이 없음
- MustRunAs 를 사용하여 허용할 그룹 ID, 사용자를 제한할 수 있다

#### MustRunAs 규칙 사용
- ID 값의 범위를 지정하고 벗어나는 ID를 불허

#### 범위를 벗어난 사용자 ID를 가진 컨테이너 이미지가 있는 파드 배포
- 이에 대해서는 API 서버가 파드를 허용하고 kubelet은 컨테이너를 실행함
- 단 사용자 ID는 2로 바뀜(PSP가 사용자 ID를 재정의함)

#### RunAsUser 필드의 MustRunAsNonRoot 규칙
- 루트로 실행되는 컨테이너를 배포할 수 없다, 컨테이너는 runAsUser 필드를 지정해야 함, 그리고 0이 아니어야 함

### 13.3.3 allowed, default, disallowed
- 컨테이너 기능에 영향을 줌

### 13.3.4 파드가 사용할 수 있는 볼륨 유형 제한
- emptyDir, configMap, secret, downwardAPI, persistentVolumeClaim
- PSP 리소스가 여러개인 경우 리소스에 기재된 모든 유형이 사용가능함

### 13.3.5 각각의 사용자와 그룹에 다른 PSP 할당
- 클러스터롤을 클러스터롤 바인딩을 사용해 특정 사용자나 그룹에 바인딩할 수 있다

## 13.4 파드 네트워크 격리
- NetworkPolicy 리소스: 인그레스, 이그레스 규칙으로 구성
- <파드 셀렉터, 네임스페이스 셀렉터와 일피하는 파드> 또는 <CIDR 표기법을 사용해 지정된 네트워크 IP 대역과 일치하는 파드>에 적용된다
### 13.4.1 네임스페이스에서 네트워크 격리 사용
- default-deny NetworkPolicy: 아무도 해당 네임스페이스의 파드에 연결할 수 없다
```yaml
piVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector:
```

### 13.4.2 네임스페이스 일부 클라이언트 파드만 허용
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-netpolicy
spec:
  podSelector:
    matchLabels:
      app: database        ## policy를 적용할 파드
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webserver  ## 허용할 파드
    ports:
    - port: 5432             ## 허용하는 port
```

### 13.4.3 쿠버네티스 네임스페이스 간 네트워크 격리
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shoppingcart-netpolicy
spec:
  podSelector:
    matchLabels:
      app: shopping-cart 
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          tenant: manning
    ports:
    - port: 80
```
- name: shoppingcart-netpolicy 레이블의 파드는 tenant: manning 레이블을 가지는 네임스페이스의 파드만 액세스 가능

### 13.4.4 CIDR 표기법으로 격리
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipblock-netpolicy
spec:
  podSelector:
    matchLabels:
      app: shopping-cart
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24
```
- name: ipblock-netpolicy 레이블의 파드는 cidr: 192.168.1.0/24 대역의 클라이언트만 허용

### 13.4.5 파드의 아웃바운드 트래픽 제한
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-net-policy
spec:
  podSelector:
    matchLabels:
      app: webserver
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database
    ports:
    - port: 5432
```
- name: egress-net-policy 레이블의 파드가 app: database 파드의 5432 포트에만 액세스할 수 있다
