### ISSUE TITLE
21주

### ISSUE THREAD

**Issue by lndoorshoes** [lndoorshoes/study#7]
# 14 파드의 컴퓨팅 리소스 관리
## 14.1 파드 컨테이너의 리소스 요청
- 파드 생성 시 컨테이너가 사용할 CPU와 메모리 양에 제한을 걸 수 있다
- 파드의 리소스 요청과 제한 = 컨테이너 리소스 요청과 제한의 합

### 14.1.1 리소스 요청을 갖는 파드 생성
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: requests-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      requests:
        cpu: 200m
        memory: 10Mi
```
- CPU request를 지정하지않으면 최악의 경우 CPU 시간을 전혀 할당받지 못할 수 있다
- 먼저 request를 지정한 것이 파드 스케줄링에 어떤 영향을 주는지 살펴보자
#### 파드가 특정 노드에 실행할 수 있는지 스케줄러가 결정하는 법
- 스케줄러는 스케줄링 시점에 노드에 배포된 파드들의 리소스 요청량의 합을 본다 (실제 사용량이 아님)

#### 스케줄러가 파드가 실행될 최적의 노드를 선택할 때 파드의 request를 사용하는 법
- 스케줄러는 우선순위에 따라 노드의 우선순위를 지정함
- 우선순위 함수 = LeastRequestedPriority, MostRequestedPriority
- LeastRequestedPriority: 요청된 리소스양이 가장 작은 노드
- MostRequestedPriority: 요청된 리소스양이 많은 노드 선호 (적은 수의 노드를 사용하기에 적합함, 비용 절감)
- 둘 중 하나만을 사용함

#### 노드의 용량 검사
```
$ kubectl describe nodes

Capacity:
  cpu:                6
  ephemeral-storage:  61255492Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             2034968Ki
  pods:               110
Allocatable:
  cpu:                6
  ephemeral-storage:  61255492Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             2034968Ki
  pods:               110
```

#### 어느 노드에서 실행할 수 없는 파드
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  15s   default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
```

### 14.1.3 CPU 요청이 CPU 시간 공유에 미치는 영향
- CPU 요청은 CPU 시간을 파드간 분배하는 방식도 결정함 (요청 비율만큼 할당함)
- 하지만 요청이 적은 파드라도 요청이 많은 파드가 유휴 상태라면 필요한만큼 리소스를 사용할 수 있다

### 14.1.4 사용자 정의 리소스의 정의와 요청
- PATCH HTTP를 이용하여 노드 오브젝트의 capacity 필드에 사용자 정의 리소스를 추가
- 수량은 정수여야 한다
- 그런 다음 파드를 생성할 때 resources.requests 필드로 지정
- 일련의 과정을 통해 사용자 정의 리소스 관리 가능

#### 제한이 필요한 이유
- CPU는 압축 가능한 리소스로 제한하더라도 컨테이너에서 실행 중인 프로세스에 부정적인 영향을 주지 않을 수 있다
- 하지만 메모리는 프로세스가 메모리를 헤제하지 않는 한 다른 측에서 가져갈 수 없기 때문에 제한이 필요하다

#### 리소스 제한을 갖는 파드 생성
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: requests-pod
spec:
  containers:
  - image: busybox
    command: ["dd", "if=/dev/zero", "of=/dev/null"]
    name: main
    resources:
      limits:
        cpu: 1
        memory: 20Mi
```

#### 리소스 제한 오버커밋
- 리소스 제한의 합계는 노드 용량의 100%를 초과할 수 있다
- 노드 리소스가 모두 소진되면 특정 컨테이너는 제거 된다

#### 14.2.2 리소스 제한 초과
- CPU는 일반적으로 모든 CPU 시간을 사용하게 된다. 제한된 CPU 시간 보다는 많이 받지 못함
- 메모리의 경우에는 제한보다 많은 메모리를 할당받으려 시도하면 프로세스가 종료된다

#### CrashLoopBackOff
- 메모리 제한 초과로 인한 종료와 재시작이 지속되면 CrashLoopBackOff 상태가 됨
- 이는 컨테이너 재시작 시간 간격을 늘리는 상태이며, 그 간격은 300초까지 점진적으로 늘어남
- 이후에는 삭제될때 까지 5분마다 재시작을 반복함

#### 컨테이너는 컨테이너 메모리가 아닌 노드 메모리를 본다
- top 명령은 컨테이너가 실행 중인 전체 노드의 메모리 양을 표시한다, 컨테이너에서는 제한을 인식할 방법이 없다
- JVM의 최대 힙 크기를 지정하지 않은 경우 컨테이너에서 사용 가능한 메모리 대신 호스트의 총 메모리를 기준으로 설정함
- Xmx 옵션은 힙 크기를 제한하지만 JVM의 오프 힙 메모리에는 영향을 미치지 않는다
- 새 버전의 자바는 컨테이너 제한을 고려하므로 괜찮다

#### 컨테이너는 노드의 모든 CPU를 본다
- 앱이 시스템 CPU를 검색해 작업 스레드 수를 결정하는 경우에는 많은 수의 코어가 있는 환경에서 너무 많은 스레드로 인해 메모리 사용량이 급증할 수 있으므로, 이러한 경우를 위해서라도 CPU 제한과 메모리제한은 권장된다

## 14.3 파드 QoS 클래스 이해
- 리소스 제한은 오버 커밋될 수 있고, 노드는 모든 파드의 리소스 제한에 지정된 리소스를 제공할 수 없을 수 있다
- 가용 메모리양을 초과하는 메모리 요청이 오는 경우 어떤 컨테이너가 종료될까?
- QoS 클래스에 따라 파드를 분류한다
  - BestEffort(최하위 순위)
  - Burstable
  - Guaranteed(최상위 순위)

### 14.3.1 파드의 QoS 클래스 정의
- QoS클래스는 파드 컨테이너의 리소스 요청과 제한의 조합에서 파생된다
- besteffort = 아무 리소스 요청과 제한이 없는 컨테이너

#### guaranteed 클래스에 파드를 할당하기
- 조건
  - CPU와 메모리에 요청과 제한이 모두 설정 돼야 함
  - 각 컨테이너에 설정돼야 함
  - 리소스 요청과 제한이 모든 컨테이너에서 일치해야 함
- 요청이 명시적으로 설정되지 않으면 리소스 제한과 동일하게 설정됨

#### burstable
- 조건
  - 리소스 제한과 요청이 일치하지 않음
  - 리소스 요청을 지정했지만 제한은 설정하지 않음
- besteffort, guaranteed가 아니면 burstable이라고 생각하면 될 것

#### 다중 컨테이너의 경우
- 모든 컨테이너가 besteffort/guaranteed면 파드도 해당 QoS
- 그 밖에는 Burstable
- QoS 클래스는 status.qosClass에 표시된다

### 14.3.2 메모리가 부족할 때 어떤 프로세스가 종료될까?
- BestEffort 클래스가 먼저 종료, 다음은 Burstable 종료
- Guaranteed는 시스템 프로세스가 메모리를 필요로 하는 경우에만 종료

#### 우선순위를 정하는 방법
- Besteffort 파드의 프로세스는 Burstable 프로세스의 파드보다 항상 먼저 종료됨
- 그렇다면 파드의 QoS가 동등하면?
  - 실행 중인 프로세스는 OOM 점수를 가진다
 
#### OOM
- 계산 방법
  - 프로세스가 소비하는 가용 메모리 비율과 컨테이너의 요청된 메모리와 파드의 QoS 클래스를 기반으로 점수가 계산됨
- 결국 클래스가 같으면 요청된 메모리에 비해 사용률이 높은 컨테이너를 먼저 종료함
