### ISSUE TITLE
23주

### ISSUE THREAD

**Issue by lndoorshoes** [lndoorshoes/study#9]
# chp 15 파드와 클러스터 노드의 오토스케일링
## 15.1 수평적 파드 오토스케일링
- HPA의 대상: ReplicationController, Deployment, ReplicaSet, StatefulSet
- HPA의 대상이 아닌 것: DaemonSet
![image](https://user-images.githubusercontent.com/26867199/141793097-f2413873-5bd4-43a9-b18c-8e235bcaf2be.png)

### 개념
  - 컨트롤러 관리자의 --horizontal-pod-autoscaler-sync-period 플래그(기본값은 15초)에 의해 제어되는 주기를 가진 컨트롤 루프로 구현됨
  - HPA 정의에 지정된 메트릭에 대해 리소스 사용률을 질의하고, 컨트롤러 관리자는 리소스 메트릭, 사용자 지정 메트릭에서 정보를 가져옴

#### 1. 파드 메트릭 얻기
- cAdvisor는 노드의 모든 컨테이너에서 메트릭 수집
- 힙스터는 모든 노드에서 메트릭 수집
- Autoscaler는 힙스터에서 메트릭 수집

#### 2. 필요한 파드 수 계산
- 오토스케일링 대상인 리소스 파드들의 메트릭을 가지고 있다면 필요한 레플리카 수를 파악할 수 있다
- 모든 레플리카의 평균값을 이용해 지정한 목표 값과 가능한 가깝게 하는 숫자를 찾아야 한다

#### 3. 스케일링된 리소스의 레플리카 수 갱신
-  오토스케일링 마지막 단계는 레플리카 개수 필드를 원하는 값으로 갱신하고, 파드 수를 조절하는 것
  - API 서버가 노출하는 스케일 서브 리소스를 통해 replicas 필드를 변경한다

### 15.1.2 CPU 사용률 기반 스케일링
- CPU 사용량이 80%라는 것을 어떻게 알 수 있을까?
  - 파드가 보장 받은 CPU 사용량만이 중요하다 - 실제 사용량과 요청량을 비교함
  - 오토스케일링이 필요한 파드는 직,간접적으로 LimitRange 오브젝트를 통해 CPU request 설정해야 한다!

#### CPU 사용률을 기반으로 HPA 생성
- deployment에 CPU request 설정
```yaml
spec:
  containers:
  - image: luksa/kubia:v1
    name: nodejs
    resources:
      requests:
        cpu: 100m
```

- 간단한 autoscale 명령어
  - kubectl autoscale deployment kubia --cpu-percent=30 --min=1 --max=5
- HPA 정의
  - apiVersion: autoscaling/v1
```yaml
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 30
    type: Resource
  minReplicas: 1
  scaleTargetRef:   ## 타겟
    apiVersion: extensions/v1
    kind: Deployment
    name: kubia
```

#### 최초 오토 리스케일 이벤트 보기
- kubectl describe hpa kubia에서 이벤트 확인 가능

#### 스케일 업 일으키기
- 동시에 여러 리소스 관찰하기: watch -n 1 kubectl get hpa, deployment
- 108%라는 CPU 사용률이 나오면
  - 이것을 목표 사용률인 30으로 나누고
  - 3.6을 반올림하여 4를 만든뒤 예상 사용률 108/4 약 27을 얻게 된다
  - 따라서 4개의 replica를 가지는 상태가 된것을 유추할 수 있다

#### 최대 스케일링 비율
- 2개를 초과하는 레플리카가 존재하면 한번의 수행에서 최대 두배까지 추가 생성 가능
- 1, 2개인 경우에는 4개까지만 확장될 수 있다
- 오토스케일 작업간 간격에 대한 제한도 있다(스케일업은 최소 3분, 스케일다운은 최소 5분)

### 15.1.3 메모리 소비량에 기반을 둔 스케일링
- 스케일 업 후 메모리 해제 작업이 필요해서 더 복잡함
- 공식 문서를 볼 것

#### 리소스 메트릭 유형 이해
- 오토스케일 결정을 컨테이너 리소스 요청 항목 등의 메트릭 기반으로 하도록 한다

#### 파드 메트릭
- 초당 질의 수, 메시지 브로커의 큐 메시지 수 등
```yaml
metrics:
  - type: Pods
    resource:
      metricName: qps
      targetAverageValue: 100
```

#### 오브젝트 메트릭 유형
- 파드에 직접 관련되지 않는 메트릭, 인그레스 오브젝트 같은 클러스터 오브젝트 메트릭

### 15.1.5 오토스케일링에 적합한 메트릭 결정
- 컨테이너 메모리 소비량은 레플리카 수를 늘려도 변화를 기대하기 어려울 수 있다
- X 값이 늘어난 레플리카 수 만큼의 변화가 있는 것이 좋다

### 15.1.6 레플리카를 0으로 감소
- 특정 파드 레플리카를 0으로 감소할 수 있게 하는 기능(유휴, 유휴 해제)
- 아직은 없다

## 15.2 수직적 파드 오토스케일링
- 앞으로 기대하는 기능임
### 15.2.1 리소스 요청 자동 설정
- 새 기능은 CPU와 메모리 요청이 명시적이지 않은 경우 이를 설정하는 것

## 15.3 수평적 클러스터 노드 확장
- 새 파드를 수용하지 못하는 상태
- 온프레미스 환경: 새로운 머신 추가
- 클라우드 인프라스트럭쳐: 클릭과 API
#### 클라우드 인프라스트럭처에 추가 노드 요청
- 스케줄러가 새 파드를 스케줄링할 수 없을 때 새로운 노드 공급
  - 새로운 노드가 파드를 수용할 수 있는지 확인함
- 클러스터 오토스케일러는 노드 유형을 지정하여 노드 요청

#### 노드 종료 (스케일 다운)
- 노드 리소스가 충분히 활용되고 있지 않을 때 = 모든 파드의 CPU와 메모리 요청이 50%미만일 때
- 해당 노드에서만 실행 중인 시스템 파드가 있을 때, 관리되지 않는 파드나, 로컬 저장소를 가진 파드가 실행되는 경우(서비스 중단 방지)

### 15.3.2 클러스터 오토스케일러 활성화
- 클라우드 공급사의 경우 명령어로 가능함
### 클러스터 스케일 다운 동안에 서비스 중단 제한
- 노드 종료가 의도된 것일 때는 해당 노드의 파드가 제공하는 서비스가 중단되지 않도록 할 수 있다
- 스케일 다운 시 유지돼야하는 최소 파드 개수 지정 - PodDisruptionBudget 리소스로 가능
  - kubectl create pdb kubia-pdb --selector=app=kubia --min-available=3 
  - 파드를 제거하기 전에 새파드를 띄우고 교체 한다
